name: SteelBuild
version: 0.1
author: TNYCL
main: com.steel.Main
commands:
  proje:
    description: Proje sistemi
  product:
    description: Proje sistemi
  user:
    description: Üye sistemi
  üye:
    description: Üye sistemi
